name: Run linters on PRs

on:
  pull_request:
    branches:
      - v2  # TODO: Remove!
      - development
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use the Ruff linter to annotate code style / best-practice issues
      # NOTE: More config provided in pyproject.toml
      - name: Lint and annotate PR
        uses: chartboost/ruff-action@v1
        with:
          args: "check . --output-format github"
